_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.0
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 512
capture_video:
    value: false
clip_coef:
    value: 0.2
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0.01
exp_name:
    value: ppo
gae:
    value: true
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
gym_id:
    value: SuperMarioBrosRandomStages-v0
learning_rate:
    value: 0.00025
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 128
norm_adv:
    value: true
num_envs:
    value: 4
num_minibatches:
    value: 4
num_steps:
    value: 128
seed:
    value: 1
target_kl:
    value: null
torch_deterministic:
    value: true
total_time_step:
    value: 25000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_project_name:
    value: ppo-implementation-details
